Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

    enable_nfs = false

    if !Vagrant::Util::Platform.windows?
        enable_nfs = true
    end

    if Vagrant.has_plugin?("vagrant-vbguest")
        config.vbguest.auto_update = false
    end

    config.vm.provider :virtualbox do |v|
        v.name = "testansibleroleopenresty"
        v.customize [
            "modifyvm", :id,
            "--name", "testansibleroleopenresty",
            "--memory", 512,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
            "--cpuexecutioncap", 95
        ]
    end

    config.vm.box = "ubuntu/xenial64"
    
    config.vm.provision "ansible" do |ansible|
        ansible.groups = {
          "source" => ["machine1"]
        }
        # ansible.verbose = true
        ansible.playbook = "test.yml"
    end

end
